const ProductActionTypes = {
    SET_PRODUCTS : 'SET_PRODUCTS',
    FETCH_PRODUCT_START : 'FETCH_PRODUCT_START',
    FETCH_PRODUCT_SUCCESS : 'FETCH_PRODUCT_SUCCESS',
    FETCH_PRODUCT_FAILURE : 'FETCH_PRODUCT_FAILURE',
}

export default ProductActionTypes;